name: colorfy
description: Terminal string styling done right with Dart.
version: 1.0.0
repository: https://github.com/jeanluc243/colorfy

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
